---
- name: Install hadoop on master 
  hosts: "{ hostname_master }}"
  remote_user:"{{ remote_user }}"
  sudo: True

  roles:
    - java
    - hadoop_master
   
- name: Install hadoop on slave 
  hosts: "{{ hostname_slave }}"
  remote_user: "{{ remote_user }}"
  sudo: True

  roles:
    - java
    - hadoop_slave
